### ISSUE TITLE
 本地 python 环境冲突

### ISSUE THREAD

**Issue by JiapengLi** [makerdiary/terminal-s#1]
本地装有 python 环境运行时出错，貌似冲突了。不知道是什么原因。
```
$ ./terminal-s.exe
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 17, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "C:\hostedtoolcache\windows\Python\3.8.2\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrect.
[20776] Failed to execute script pyi_rth_multiprocessing
```

**Comment by xiongyihui** [comment]
可能被我裁掉了一些包，依赖缺失了

**Comment by xiongyihui** [comment]
0.1.2版本的应该可以用了，改一个干净的虚拟机里试过
之前打包，依赖却了几个

**Comment by JiapengLi** [comment]
我这边还是不行，有可能是我本地环境的问题。我本地有个 python 3.8 的环境。貌似这个打包的软件先从我本地加载库。 怀疑是 PyInstaller 打包之后优先加载本地库？

**Comment by xiongyihui** [comment]
有可能，可能PyInstaller的版本不兼容，然后出错了。
那直接用 pip 安装吧
